//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UILang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UILang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClientApp.Resources.UILang", typeof(UILang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Checked {
            get {
                object obj = ResourceManager.GetObject("Checked", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный логин или пароль.
        /// </summary>
        public static string Error_BadLoginPassword {
            get {
                return ResourceManager.GetString("Error_BadLoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введенные пароли не совпадают. Проверьте ввод..
        /// </summary>
        public static string Error_PasswordsAreNotTheSame {
            get {
                return ResourceManager.GetString("Error_PasswordsAreNotTheSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as.
        /// </summary>
        public static string qw {
            get {
                return ResourceManager.GetString("qw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторизация.
        /// </summary>
        public static string UI_AuthPage_AuthorizationHeader {
            get {
                return ResourceManager.GetString("UI_AuthPage_AuthorizationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string UI_AuthPage_Enter {
            get {
                return ResourceManager.GetString("UI_AuthPage_Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин:.
        /// </summary>
        public static string UI_AuthPage_LoginField {
            get {
                return ResourceManager.GetString("UI_AuthPage_LoginField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль:.
        /// </summary>
        public static string UI_AuthPage_PasswordField {
            get {
                return ResourceManager.GetString("UI_AuthPage_PasswordField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string UI_ErrorDlg_Caption {
            get {
                return ResourceManager.GetString("UI_ErrorDlg_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжить.
        /// </summary>
        public static string UI_FirstLoginPage_Continue_Button {
            get {
                return ResourceManager.GetString("UI_FirstLoginPage_Continue_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы выполнили первый вход в систему B2B Market или ваш пароль был сброшен администратором..
        /// </summary>
        public static string UI_FirstLoginPage_Info1 {
            get {
                return ResourceManager.GetString("UI_FirstLoginPage_Info1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите новый личный пароль для входа в систему:.
        /// </summary>
        public static string UI_FirstLoginPage_Info2 {
            get {
                return ResourceManager.GetString("UI_FirstLoginPage_Info2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пароль:.
        /// </summary>
        public static string UI_FirstLoginPage_Password1_Field {
            get {
                return ResourceManager.GetString("UI_FirstLoginPage_Password1_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите еще раз:.
        /// </summary>
        public static string UI_FirstLoginPage_Password2_Field {
            get {
                return ResourceManager.GetString("UI_FirstLoginPage_Password2_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать в В2В Market!.
        /// </summary>
        public static string UI_FirstLoginPage_Welcome {
            get {
                return ResourceManager.GetString("UI_FirstLoginPage_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] UI_Image_Favorite_Off {
            get {
                object obj = ResourceManager.GetObject("UI_Image_Favorite_Off", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] UI_Image_Favorite_On {
            get {
                object obj = ResourceManager.GetObject("UI_Image_Favorite_On", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B2B Market.
        /// </summary>
        public static string UI_MainWindow_Title {
            get {
                return ResourceManager.GetString("UI_MainWindow_Title", resourceCulture);
            }
        }
    }
}
