//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UILang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UILang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClientApp.Resources.UILang", typeof(UILang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Contracted {
            get {
                object obj = ResourceManager.GetObject("Contracted", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] EmptyPicture {
            get {
                object obj = ResourceManager.GetObject("EmptyPicture", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный логин или пароль.
        /// </summary>
        public static string Error_BadLoginPassword {
            get {
                return ResourceManager.GetString("Error_BadLoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введенные пароли не совпадают. Проверьте ввод..
        /// </summary>
        public static string Error_PasswordsAreNotTheSame {
            get {
                return ResourceManager.GetString("Error_PasswordsAreNotTheSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Minus_Disabled {
            get {
                object obj = ResourceManager.GetObject("Minus_Disabled", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Minus_Enabled {
            get {
                object obj = ResourceManager.GetObject("Minus_Enabled", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Navigation_Back {
            get {
                object obj = ResourceManager.GetObject("Navigation_Back", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Navigation_Forward_Gray {
            get {
                object obj = ResourceManager.GetObject("Navigation_Forward_Gray", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Plus_Disabled {
            get {
                object obj = ResourceManager.GetObject("Plus_Disabled", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Plus_Enabled {
            get {
                object obj = ResourceManager.GetObject("Plus_Enabled", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Search {
            get {
                object obj = ResourceManager.GetObject("Search", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторизация.
        /// </summary>
        public static string UI_AuthPage_AuthorizationHeader {
            get {
                return ResourceManager.GetString("UI_AuthPage_AuthorizationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string UI_AuthPage_Enter {
            get {
                return ResourceManager.GetString("UI_AuthPage_Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин:.
        /// </summary>
        public static string UI_AuthPage_LoginField {
            get {
                return ResourceManager.GetString("UI_AuthPage_LoginField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль:.
        /// </summary>
        public static string UI_AuthPage_PasswordField {
            get {
                return ResourceManager.GetString("UI_AuthPage_PasswordField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все товары.
        /// </summary>
        public static string UI_CategoriesSubPage_AllProducts {
            get {
                return ResourceManager.GetString("UI_CategoriesSubPage_AllProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string UI_ErrorDlg_Caption {
            get {
                return ResourceManager.GetString("UI_ErrorDlg_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжить.
        /// </summary>
        public static string UI_FirstLoginPage_Continue_Button {
            get {
                return ResourceManager.GetString("UI_FirstLoginPage_Continue_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы выполнили первый вход в систему B2B Market или ваш пароль был сброшен администратором..
        /// </summary>
        public static string UI_FirstLoginPage_Info1 {
            get {
                return ResourceManager.GetString("UI_FirstLoginPage_Info1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите новый личный пароль для входа в систему:.
        /// </summary>
        public static string UI_FirstLoginPage_Info2 {
            get {
                return ResourceManager.GetString("UI_FirstLoginPage_Info2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пароль:.
        /// </summary>
        public static string UI_FirstLoginPage_Password1_Field {
            get {
                return ResourceManager.GetString("UI_FirstLoginPage_Password1_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите еще раз:.
        /// </summary>
        public static string UI_FirstLoginPage_Password2_Field {
            get {
                return ResourceManager.GetString("UI_FirstLoginPage_Password2_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать в В2В Market!.
        /// </summary>
        public static string UI_FirstLoginPage_Welcome {
            get {
                return ResourceManager.GetString("UI_FirstLoginPage_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] UI_Image_Favorite_Off {
            get {
                object obj = ResourceManager.GetObject("UI_Image_Favorite_Off", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] UI_Image_Favorite_On {
            get {
                object obj = ResourceManager.GetObject("UI_Image_Favorite_On", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История заказов.
        /// </summary>
        public static string UI_MainPage_ArchivedRequestsButton {
            get {
                return ResourceManager.GetString("UI_MainPage_ArchivedRequestsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущая заявка.
        /// </summary>
        public static string UI_MainPage_CurrentRequestButton {
            get {
                return ResourceManager.GetString("UI_MainPage_CurrentRequestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избранное.
        /// </summary>
        public static string UI_MainPage_FavoritesButton {
            get {
                return ResourceManager.GetString("UI_MainPage_FavoritesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        public static string UI_MainPage_MainButton {
            get {
                return ResourceManager.GetString("UI_MainPage_MainButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск.
        /// </summary>
        public static string UI_MainPage_SearchButton {
            get {
                return ResourceManager.GetString("UI_MainPage_SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Договора с нами.
        /// </summary>
        public static string UI_MainSubPage_AllContractedSuppliers {
            get {
                return ResourceManager.GetString("UI_MainSubPage_AllContractedSuppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КАТЕГОРИИ.
        /// </summary>
        public static string UI_MainSubPage_Categories {
            get {
                return ResourceManager.GetString("UI_MainSubPage_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПОСТАВЩИКИ.
        /// </summary>
        public static string UI_MainSubPage_Suppliers {
            get {
                return ResourceManager.GetString("UI_MainSubPage_Suppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать в B2B Market, .
        /// </summary>
        public static string UI_MainSubPage_Welcome {
            get {
                return ResourceManager.GetString("UI_MainSubPage_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B2B Market.
        /// </summary>
        public static string UI_MainWindow_Title {
            get {
                return ResourceManager.GetString("UI_MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внимание!.
        /// </summary>
        public static string UI_ProductSubPage_HasChangesDlgCaption {
            get {
                return ResourceManager.GetString("UI_ProductSubPage_HasChangesDlgCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внимание! Изменения, которые вы сделали, не сохранены и будут сброшены при переходе с этой страницы.
        /// </summary>
        public static string UI_ProductSubPage_HasChangesDlgText {
            get {
                return ResourceManager.GetString("UI_ProductSubPage_HasChangesDlgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПРЕДЛОЖЕНИЯ.
        /// </summary>
        public static string UI_ProductSubPage_Offers {
            get {
                return ResourceManager.GetString("UI_ProductSubPage_Offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВНЕСТИ ИЗМЕНЕНИЯ В ЗАЯВКУ.
        /// </summary>
        public static string UI_ProductSubPage_UpdateCurrentRequest {
            get {
                return ResourceManager.GetString("UI_ProductSubPage_UpdateCurrentRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to по категориям.
        /// </summary>
        public static string UI_RequestSubPage_GroupingByCategories {
            get {
                return ResourceManager.GetString("UI_RequestSubPage_GroupingByCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to по поставщикам.
        /// </summary>
        public static string UI_RequestSubPage_GroupingBySuppliers {
            get {
                return ResourceManager.GetString("UI_RequestSubPage_GroupingBySuppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результаты поиска.
        /// </summary>
        public static string UI_SearchSubPage_SearchResults {
            get {
                return ResourceManager.GetString("UI_SearchSubPage_SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск товара.
        /// </summary>
        public static string UI_SubPages_SearchHint {
            get {
                return ResourceManager.GetString("UI_SubPages_SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] UserSettings {
            get {
                object obj = ResourceManager.GetObject("UserSettings", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
