//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administration_Tools.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UILang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UILang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Administration_Tools.Resources.UILang", typeof(UILang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string UI_AddContractWithClientDlg_AddClient {
            get {
                return ResourceManager.GetString("UI_AddContractWithClientDlg_AddClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string UI_AddContractWithClientDlg_Cancel {
            get {
                return ResourceManager.GetString("UI_AddContractWithClientDlg_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список доступных клиентов:.
        /// </summary>
        public static string UI_AddContractWithClientDlg_ClientsListHeader {
            get {
                return ResourceManager.GetString("UI_AddContractWithClientDlg_ClientsListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить договор клиента....
        /// </summary>
        public static string UI_AddContractWithClientDlg_Title {
            get {
                return ResourceManager.GetString("UI_AddContractWithClientDlg_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string UI_Clients_AddClient {
            get {
                return ResourceManager.GetString("UI_Clients_AddClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес:.
        /// </summary>
        public static string UI_Clients_Address_Field {
            get {
                return ResourceManager.GetString("UI_Clients_Address_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to БИН:.
        /// </summary>
        public static string UI_Clients_BIN_Field {
            get {
                return ResourceManager.GetString("UI_Clients_BIN_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список клиентов:.
        /// </summary>
        public static string UI_Clients_ClientsListHeader {
            get {
                return ResourceManager.GetString("UI_Clients_ClientsListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Договора с поставщиками:.
        /// </summary>
        public static string UI_Clients_ContractsListHeader {
            get {
                return ResourceManager.GetString("UI_Clients_ContractsListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-mail:.
        /// </summary>
        public static string UI_Clients_Email_Field {
            get {
                return ResourceManager.GetString("UI_Clients_Email_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полное название:.
        /// </summary>
        public static string UI_Clients_FullName_Field {
            get {
                return ResourceManager.GetString("UI_Clients_FullName_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID:.
        /// </summary>
        public static string UI_Clients_Id_Field {
            get {
                return ResourceManager.GetString("UI_Clients_Id_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тел.:.
        /// </summary>
        public static string UI_Clients_Phone_Field {
            get {
                return ResourceManager.GetString("UI_Clients_Phone_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string UI_Clients_RemoveClient {
            get {
                return ResourceManager.GetString("UI_Clients_RemoveClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить изменения.
        /// </summary>
        public static string UI_Clients_SaveChanges {
            get {
                return ResourceManager.GetString("UI_Clients_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Короткое имя:.
        /// </summary>
        public static string UI_Clients_ShortName_Field {
            get {
                return ResourceManager.GetString("UI_Clients_ShortName_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        public static string UI_Clients_UpdateClientsListButton {
            get {
                return ResourceManager.GetString("UI_Clients_UpdateClientsListButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клиенты.
        /// </summary>
        public static string UI_MainWindow_ClientsButton {
            get {
                return ResourceManager.GetString("UI_MainWindow_ClientsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поставщики.
        /// </summary>
        public static string UI_MainWindow_SuppliersButton {
            get {
                return ResourceManager.GetString("UI_MainWindow_SuppliersButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B2B Market - Панель администратора.
        /// </summary>
        public static string UI_MainWindow_Title {
            get {
                return ResourceManager.GetString("UI_MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string UI_Suppliers_AddContract {
            get {
                return ResourceManager.GetString("UI_Suppliers_AddContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес:.
        /// </summary>
        public static string UI_Suppliers_Address_Field {
            get {
                return ResourceManager.GetString("UI_Suppliers_Address_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string UI_Suppliers_AddSupplier {
            get {
                return ResourceManager.GetString("UI_Suppliers_AddSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to БИН:.
        /// </summary>
        public static string UI_Suppliers_BIN_Field {
            get {
                return ResourceManager.GetString("UI_Suppliers_BIN_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Договора с клиентами:.
        /// </summary>
        public static string UI_Suppliers_ContractsListHeader {
            get {
                return ResourceManager.GetString("UI_Suppliers_ContractsListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-mail:.
        /// </summary>
        public static string UI_Suppliers_Email_Field {
            get {
                return ResourceManager.GetString("UI_Suppliers_Email_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полное название:.
        /// </summary>
        public static string UI_Suppliers_FullName_Field {
            get {
                return ResourceManager.GetString("UI_Suppliers_FullName_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID:.
        /// </summary>
        public static string UI_Suppliers_Id_Field {
            get {
                return ResourceManager.GetString("UI_Suppliers_Id_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тел.:.
        /// </summary>
        public static string UI_Suppliers_Phone_Field {
            get {
                return ResourceManager.GetString("UI_Suppliers_Phone_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string UI_Suppliers_RemoveContract {
            get {
                return ResourceManager.GetString("UI_Suppliers_RemoveContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string UI_Suppliers_RemoveSupplier {
            get {
                return ResourceManager.GetString("UI_Suppliers_RemoveSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить изменения.
        /// </summary>
        public static string UI_Suppliers_SaveChanges {
            get {
                return ResourceManager.GetString("UI_Suppliers_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Короткое имя:.
        /// </summary>
        public static string UI_Suppliers_ShortName_Field {
            get {
                return ResourceManager.GetString("UI_Suppliers_ShortName_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список поставщиков:.
        /// </summary>
        public static string UI_Suppliers_SuppliersListHeader {
            get {
                return ResourceManager.GetString("UI_Suppliers_SuppliersListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        public static string UI_Suppliers_UpdateSuppliersListButton {
            get {
                return ResourceManager.GetString("UI_Suppliers_UpdateSuppliersListButton", resourceCulture);
            }
        }
    }
}
